version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: strapidb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - strapi-net
  strapi:
    build: .
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: strapidb
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      CLOUDINARY_CLOUD_NAME: dcervellon-dev
      CLOUDINARY_API_KEY: 378981442268235
      CLOUDINARY_API_SECRET: R_ei0suwHQKZVPNrYe6d4TOJqBQ
    ports:
      - "1337:1337"
    depends_on:
      - postgres
    networks:
      - strapi-net
networks:
  strapi-net:

